# Generated by Django 3.2.16 on 2023-01-22 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_date', models.IntegerField(default=3)),
                ('send_mail_date', models.IntegerField(default=-2)),
                ('sender_mail', models.EmailField(max_length=254)),
                ('sender_mail_status', models.BooleanField(default=0)),
                ('delete_date_status', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry', models.CharField(blank=True, max_length=60, null=True)),
                ('is_show', models.BooleanField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=60, null=True)),
                ('is_show', models.BooleanField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verify_Certificatefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.FileField(max_length=200, upload_to='verify_certificate/')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('editing_message', models.TextField(blank=True, null=True)),
                ('user_create', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=7, null=True)),
                ('cal_date', models.DateField(blank=True, null=True)),
                ('send_email', models.BooleanField(blank=True, null=True)),
                ('is_upload', models.BooleanField(default=0)),
                ('number', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=70, null=True)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general_app.ministry')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general_app.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.FileField(max_length=200, upload_to='%Y/')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('download_date', models.DateField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
