# Generated by Django 3.2.16 on 2023-01-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='send_email',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
