# Generated by Django 3.2.16 on 2023-01-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0002_alter_user_detail_send_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_detail',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='user_detail',
            table='user_detail',
        ),
    ]
