# Generated by Django 3.2.16 on 2023-01-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0003_auto_20230124_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatefile',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='certificatefile',
            table='certificatefile',
        ),
    ]
