# Generated by Django 3.2.16 on 2023-01-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0004_auto_20230124_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatefile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user_detail',
            options={},
        ),
        migrations.AlterModelTable(
            name='certificatefile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user_detail',
            table=None,
        ),
    ]
