# Generated by Django 3.2.16 on 2023-01-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0005_auto_20230125_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='sender_mail',
        ),
    ]
